HPCC-13540 Attempt to fix 12780 regression
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>

diff --git a/initfiles/componentfiles/thor/start_slaves b/initfiles/componentfiles/thor/start_slaves
--- a/initfiles/componentfiles/thor/start_slaves
+++ b/initfiles/componentfiles/thor/start_slaves
@@ -68,8 +68,10 @@ done
 trap "rm -f $lckfile" exit
 echo $$ > $lckfile
 
-
-
+ulimit -c unlimited > /dev/null 2>&1
+[[ $? -ne 0 ]] && echo "`date` Failed to set ulimit for core file size"
+ulimit -n 32768 > /dev/null 2>&1
+[[ $? -ne 0 ]] && echo "`date` Failed to set ulimit for number of file descriptors open"
 
 echo "`date` slave(s) starting"
 
