HPCC-27051 Create a Sasha service to clean up post-mortem files
Remove kubectl describe replicaset; determine debugplane-housekeeping pod name


Signed-off-by: Dave Streeter <dave.streeter@lexisnexisrisk.com>

diff --git a/.github/actions/deploy-hpcc-k8s/action.yaml b/.github/actions/deploy-hpcc-k8s/action.yaml
--- a/.github/actions/deploy-hpcc-k8s/action.yaml
+++ b/.github/actions/deploy-hpcc-k8s/action.yaml
@@ -164,29 +164,21 @@ runs:
             echo "kubectl get pods"
             kubectl get pods
 
+            echo "Determine sasha-debugplane pod name"
+            dbgpod=$(kubectl get pods --no-headers | awk '/^sasha-debugplane/ { print $1 }')
+            echo "sasha-debugplane pod name: $dbgpod"
+
+            echo "sasha-debugplane: kubectl get: $dbgpod"
+            kubectl get $dbgpod -o yaml
+
+            echo "sasha-debugplane: kubectl describe pod: $dbgpod"
+            kubectl describe pod $dbgpod
+
+            echo "Getting recent logs from $dbgpod"
+            kubectl logs --tail=50 $dbgpod || echo "Failed to get logs for $dbgpod"
+
             echo "kubectl get rs"
             kubectl get rs
-            
-            echo "kubectl describe rs"
-            kubectl get rs | awk 'NR>1 {print $1}' | while read -r rsname; do
-              kubectl describe replicaset/$rsname
-            done
-            
-            echo "Fetching pods for deployment $i..."
-            pods=$(kubectl get pods --selector=app=${i#*/} -o name)
-            
-            if [ -z "$pods" ]; then
-              echo "No pods found for deployment $i"
-            else
-              for pod in $pods; do
-                podname=${pod#deployment.apps/}
-                echo "Describing $podname"
-                kubectl describe $podname
-                
-                echo "Getting recent logs from $podname"
-                kubectl logs --tail=50 $podname || echo "Failed to get logs for $podname"
-              done
-            fi
             
             exit 1
           fi
