Update action.yaml
Remove debugplane specific actions and replace with actions for all pods

diff --git a/.github/actions/deploy-hpcc-k8s/action.yaml b/.github/actions/deploy-hpcc-k8s/action.yaml
--- a/.github/actions/deploy-hpcc-k8s/action.yaml
+++ b/.github/actions/deploy-hpcc-k8s/action.yaml
@@ -164,18 +164,19 @@ runs:
             echo "kubectl get pods"
             kubectl get pods
 
-            echo "Determine sasha-debugplane pod name"
-            dbgpod=$(kubectl get pods --no-headers | awk '/^sasha-debugplane/ { print $1 }')
-            echo "sasha-debugplane pod name: $dbgpod"
-
-            echo "sasha-debugplane: kubectl get pod $dbgpod"
-            kubectl get pod $dbgpod -o yaml || true
-
-            echo "sasha-debugplane: kubectl describe pod $dbgpod"
-            kubectl describe pod $dbgpod || true
-
-            echo "Getting recent logs from $dbgpod"
-            kubectl logs --tail=50 $dbgpod || echo "Failed to get logs for $dbgpod"
+            echo "Getting information for all pods"
+            for pod in $(kubectl get pods --no-headers | awk '{ print $1 }'); do
+              echo "Pod name: $pod"
+			  
+              echo "$pod: kubectl get pod"
+              kubectl get pod $pod -o yaml || true
+			  
+			        echo "$pod: kubectl describe pod"
+              kubectl describe pod $pod || true
+			  
+      			  echo "$pod: getting recents logs"
+              kubectl logs --tail=50 $pod || echo "Failed to get logs for $pod"
+            done
 
             echo "kubectl get rs"
             kubectl get rs
