HPCC-23054 Thor on demand
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

diff --git a/initfiles/bash/etc/init.d/hpcc_common.in b/initfiles/bash/etc/init.d/hpcc_common.in
--- a/initfiles/bash/etc/init.d/hpcc_common.in
+++ b/initfiles/bash/etc/init.d/hpcc_common.in
@@ -422,10 +422,22 @@ start_dafilesrv() {
 function getUserLimits() {
     local flag=$1
     local name=$2
+    local lfile=""
+    if [[ $# -eq 3 ]]; then
+        lfile=$3
+    fi
     local myid=$(id -u 2>/dev/null)
     local rc=0
     if [[ "${myid}" = "0" ]] ; then
-        limit_user=$(su - ${user} -c "bash -c \"ulimit ${flag}\"" 2>/dev/null)
+        # try get limit_user from $lfile ...
+        if [[ -n "${lfile}" && -f "${lfile}" ]]; then
+            if [[ "${flag:1:1}" == "H" ]]; then
+                flag="-${flag:2:2}"
+            fi
+            limit_user=$(grep "\\${flag})" ${lfile} 2>/dev/null | awk '{print $NF}')
+        else
+            limit_user=$(su - ${user} -c "bash -c \"ulimit ${flag}\"" 2>/dev/null)
+        fi
         rc=$?
         if [[ $rc -ne 0 || -z "${limit_user}" ]] ; then
             limit_user=$(grep "${user}* hard* ${name}" /etc/security/limits.d/*.conf 2>/dev/null | tail -n 1 | awk '{print $4}')
@@ -450,7 +462,11 @@ function getUserLimits() {
 
 startCmd() {
     noStatusCheck=$2
-    printf "Starting %-21s" "$compName ..."
+    ods=""
+    if [[ "${compType}" =~ "ondemand" ]] ; then
+      ods="[OD] "
+    fi
+    printf "Starting %-21s" "$compName ${ods}..."
     log "compType = $compType"
 
     local WAITTIME=120
@@ -518,6 +534,13 @@ startCmd() {
       MIN_Hr_rtprio="4"
       MIN_Hl_memlock="unlimited" )
 
+    local limfile=""
+    local myid=$(id -u 2>/dev/null)
+    if [[ "${myid}" == "0" && -n "${user}" && "${user}" != "root" ]] ; then
+        limfile="/tmp/limfile$$"
+        su - ${user} -c "bash -c \"ulimit -Ha\" 2>/dev/null" > ${limfile}
+    fi
+
     local i=0
     local rc=0
     for element in "${limits[@]}"; do
@@ -526,7 +549,7 @@ startCmd() {
         local name=${nam1##*_}
         local value=${element##*"="}
 
-        default_value=$(getUserLimits $flag $name)
+        default_value=$(getUserLimits $flag $name $limfile)
 
         new_value=$default_value
         if [[ "$default_value" == "-2" ]] ; then
@@ -551,12 +574,22 @@ startCmd() {
         i=$((i+1))
     done
 
+    if [[ -n "${limfile}" ]]; then
+        rm -f ${limfile} > /dev/null 2>&1
+    fi
+
     UMASK_ARG=""
     if [ -n "${umask}" ]; then
         UMASK_ARG="--umask ${umask}"
     fi
 
-    EXEC_COMMAND="${bin_path}/init_${compType} "
+    # parse out -ondemand from any thor compName ...
+    compType1="${compType}"
+    if [[ "${compType1}" =~ "-ondemand" ]] ; then
+        compType1=$(echo ${compType1} | sed 's/-ondemand//g')
+    fi
+
+    EXEC_COMMAND="${bin_path}/init_${compType1} "
     startcmd="${START_STOP_DAEMON} -S -p ${pid}/init_${compName}.pid -c ${user}:${group} -d ${compPath} ${UMASK_ARG} -m -x ${EXEC_COMMAND} -b"
 
     log "${startcmd}"
@@ -577,6 +610,7 @@ startCmd() {
 
     eval $startcmd
 
+    initStarted=0
     while [[ ${WAITTIME} -gt 0 ]]; do
         WAITTIME=`expr ${WAITTIME} - 1`
         check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} ${SENTINEL_CHECK}
@@ -584,7 +618,20 @@ startCmd() {
         if [[ ${RCSTART} -eq 0 ]]; then
             log_success_msg
             return 0;
-        elif [[ ${RCSTART} -ne 4 ]]; then
+        elif [[ ${RCSTART} -eq 4 ]]; then
+            checkPidExist $PIDPATH
+            local initRunning=$__pidExists
+            if [[ $initStarted -eq 0 && $initRunning -eq 1 ]]; then
+                initStarted=1
+            fi
+            if [[ $initStarted -eq 1 && $initRunning -eq 0 ]]; then
+                # init started then ended and never started comp ...
+                log "${compName} failed to start cleanly"
+                log_failure_msg
+                cleanupRuntimeEnvironment
+                return 1;
+            fi
+        else
             checkPidExist $PIDPATH
             local initRunning=$__pidExists
             if [[ $initRunning -eq 0 ]]; then
@@ -607,7 +654,7 @@ startCmd() {
 }
 
 stop_component() {
-    printf "Stopping %-21s" "${compName}... "
+    printf "Stopping %-21s" "${compName} ... "
 
     if [ ! -d ${compPath} ] ; then
         log_success_msg
@@ -691,6 +738,21 @@ restart_component() {
         cleanupRuntimeEnvironment
       fi
       ${INIT_PATH}/dafilesrv start 2>/dev/null
+    elif [[ ${compType} =~ "-ondemand" ]]; then
+      check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
+      RCRESTART=$?
+      if [ $RCRESTART -ne 0 ];then
+        log  "$compName ---> Stopped."
+        echo "Component $compName was not running."
+        cleanupRuntimeEnvironment
+      else
+        stop_component ${compName}
+      fi
+      log   "Component ${compName} is an on-demand thor - running setup only ..."
+      echo  "Component ${compName} is an on-demand thor - running setup only ..."
+      runSetupOnly=1
+      start_component $compName
+      runSetupOnly=0
     else
       check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
       RCRESTART=$?
@@ -709,13 +771,17 @@ restart_component() {
 }
 
 status_component() {
+  ods=""
+  if [[ "${compType}" =~ "ondemand" ]] ; then
+    ods="[OD]"
+  fi
   check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
   RCSTATUS=$?
   getPid ${COMPPIDPATH}
   if [[ ${RCSTATUS} -ne 0 ]]; then
-    log "${compName} ---> Stopped"
-    printf "%-15s is stopped" "$compName"
-  elif [[ ${compType} == "thor" ]]; then
+    log "${compName} ---> Stopped ${ods}"
+    printf "%-15s is stopped" "$compName ${ods}"
+  elif [[ ${compType} =~ "thor" ]]; then
     if [[ -e ${runtime}/${compName}/slaves && -e ${runtime}/${compName}/setvars ]]; then
       source ${runtime}/${compName}/setvars
       __slaves=$(cat ${runtime}/${compName}/slaves | wc -l)
@@ -736,7 +802,23 @@ status_component() {
 
 
 setup_component() {
-    printf "Setting %-22s" "$compName.... "
+    check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
+    RCSTATUS=$?
+    if [[ ${RCSTATUS} -eq 0 ]]; then
+        stop_component ${compName}
+    fi
+    oldp=1
+    if [[ $# -ge 1 ]] ; then
+        if [[ "$1" == "start" ]] ; then
+            if [[ "${compType}" =~ "-ondemand" ]] ; then
+                oldp=0
+                printf "Skipping %-21s" "$compName [OD] ..."
+            fi
+        fi
+    fi
+    if [[ $oldp -eq 1 ]]; then
+        printf "Setting %-22s" "$compName ... "
+    fi
     runSetupOnly=1
     start_component ${compName}
     runSetupOnly=0
@@ -1053,10 +1135,12 @@ cleanup_component() {
     # grab the PID of our component, and in the case it doesn't exist, the pid of the init file (in case
     # it somehow is still alive)
     local cpidpath=${COMPPIDPATH}
-    if [ "${compType}" = "thor" ] && [ ! -f "${cpidpath}" ]; then
-        # if run_thor is sent a SIGKILL, the normal COMPPIDPATH file will no longer exist, we catch this and
-        # fall back to the {compName}_master.pid file that will still be available.
-        cpidpath=$( echo $cpidpath | sed 's/\.pid/_master.pid/' )
+    if [[ "${compType}" =~ "thor" ]]; then
+        if [ ! -f "${cpidpath}" ]; then
+            # if run_thor is sent a SIGKILL, the normal COMPPIDPATH file will no longer exist, we catch this and
+            # fall back to the {compName}_master.pid file that will still be available.
+            cpidpath=$( echo $cpidpath | sed 's/\.pid/_master.pid/' )
+        fi
     fi
     getPid ${cpidpath}
     local mpid=$__pidValue
