HPCC-13555 Changes to hpcc-init.in and hpcc_common.in for Force stop
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>

diff --git a/initfiles/bash/etc/init.d/hpcc_common.in b/initfiles/bash/etc/init.d/hpcc_common.in
--- a/initfiles/bash/etc/init.d/hpcc_common.in
+++ b/initfiles/bash/etc/init.d/hpcc_common.in
@@ -389,11 +389,10 @@ startCmd() {
     # Creating logfiles for component
     logDir=$log/${compName}
 
-    if [ ${noStatusCheck} -ne 1 ]; then
+    if [[ ${noStatusCheck} -ne 1 ]]; then
         check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 1
         RCSTART=$?
-        if [ ${RCSTART} -gt 1 ];then
-            # take care of failure message in check_status function
+        if [[ ${RCSTART} -eq 4 ]];then
             checkPidExist $PIDPATH
             local initRunning=$__pidExists
             checkPidExist $COMPPIDPATH
@@ -402,17 +401,36 @@ startCmd() {
                 log "Orphaned Process"
                 cleanup_component
                 if [[ $? -eq 1 ]]; then
+                    log "Attempt to clean up component has failed"
+                    log_failure_msg
+                    return 1
+                fi
+            fi
+            # do cleanup on successful cleanup_component return
+            # and if RCSTART -eq 4 due to lockfile still being present
+            log "Attempt to clean up component was successful"
+            cleanupRuntimeEnvironment
+        elif [[ ${RCSTART} -eq 2 ]]; then
+            log "The component $compName was previously started but is in an unhealthy state"
+            log "   Could possibly still be attempting to start.  Use the force flag to attmpt a restart"
+            if [[ ${FORCE:-NO_FORCE} == "FORCE" ]]; then
+                cleanup_component
+                if [[ $? -eq 1 ]]; then
+                    log "Attempt to clean up unleathy state of $compName failed"
                     log_failure_msg
                     return 1
                 else
-                     cleanupRuntimeEnvironment
+                    cleanupRuntimeEnvironment
                 fi
+            else
+                # component is already started but waiting to become healthy
+                log_success_msg "Waiting on sentinel file creation"
+                return 0
             fi
-        fi
-        if [ ${RCSTART} -eq 0 ]; then
+        elif [[ ${RCSTART} -eq 0 ]]; then
             #Since component is already started but current script is failed till returning 0
             log "$compName ---> already started"
-            log_success_msg "Already Started"
+            log_success_msg
             return ${RCSTART}
         fi
     fi
@@ -517,12 +535,23 @@ stop_component() {
     FAILED=0
     check_status ${PIDPATH} ${LOCKPATH} ${COMPPIDPATH} 0
     RCSTOP=$?
-    if [ $RCSTOP -ne 0 ];then
-      log "Already stopped"
-      log_success_msg "Already stopped"
-      cleanup_component
-      cleanupRuntimeEnvironment
-      return 0
+    if [[ ${RCSTOP} -eq 1 ]];then
+        log "Already stopped"
+        log_success_msg
+        return 0
+    elif [[ ${RCSTOP} -eq 4 ]]; then
+        log "Orphaned process found"
+        cleanup_component
+        local ccReturn=$?
+        if [[ ${ccReturn} -eq 0 ]]; then
+            cleanupRuntimeEnvironment
+            log_success_msg
+            return 0
+        else
+            log "Failed to clean up orphans for $compName"
+            log_failure_msg
+            return 1
+        fi
     fi
 
     stopcmd="${START_STOP_DAEMON} -K -p ${PIDPATH} >> tmp.txt 2>&1"
@@ -947,31 +976,39 @@ cleanup_component() {
         mpid=$__pidValue
     fi
 
-    # start with SIGTERM and then follow up with SIGKILL if unsuccessful
+    # start with SIGTERM and then follow up with SIGKILL if unsuccessful and force flag is set
     if [ $mpid -ne 0 ] ; then
         # use the mpid we collected to grab the group pid of the process, to kill off all siblings at once
         local pgid=$( ps -p $mpid -o pid,pgid | grep $mpid | awk '{ print $2 }' )
 
-        kill -15 -$pgid
+        kill -SIGTERM -$pgid > /dev/null 2>&1
         sleep 1
-        local WAITTIME=5
+        local WAITTIME=60
         local RUNNING=1
         while [[ ${WAITTIME} -gt 0 ]]; do
-            WAITTIME=`expr ${WAITTIME} - 1`
+            ((WAITTIME--))
             kill -0 -$pgid &> /dev/null
-            if [ $? -ne 0 ];then
+            if [[ $? -ne 0 ]];then
                 log "${compName} orphans cleaned up"
                 RUNNING=0
                 break;
             else
-                log "Waiting for ${compName} orphans to cleanup gracefully"
+                [[ "((WAITTIME % 5))" -eq 0 ]] && log "Waiting for ${compName} orphans to cleanup gracefully"
                 sleep 1
             fi
         done
 
-        if [[ ${RUNNING} -eq 1 ]]; then
-            log "sending SIGKILL to ${compName} orphans"
-            kill -9 -$pgid
+        # if still running and Force option is set, send sigkill
+        if [[ ${RUNNING} -eq 1 && ${FORCE:-NO_FORCE} == "FORCE" ]]; then
+            log "WARNING Force flag is set"
+            log "WARNING sending SIGKILL to orphans in pid group for ${compName}"
+            log "INFO    If sockets used by the process are still in a TIME_WAIT state"
+            log "INFO       due to unclean shutdown, the operating system possibly will"
+            log "INFO       not release them until 60 seconds after SIGKILL was sent"
+            kill -SIGKILL -$pgid > /dev/null 2>&1
+            [[ $? -eq 0 ]] && RUNNING=0
+        elif [[ ${RUNNING} -eq 1 && ${FORCE:-NO_FORCE} == "NO_FORCE" ]]; then
+            log "INFO    Unable to kill with SIGTERM.  Use --force|-f to attempt SIGKILL"
         fi
     fi
     return $RUNNING
