HPCC-12183 Component cleanup with 12093 dependencies
Signed-off-by: Michael Gardner <Michael.Gardner@lexisnexis.com>

diff --git a/initfiles/bash/etc/init.d/hpcc_common.in b/initfiles/bash/etc/init.d/hpcc_common.in
--- a/initfiles/bash/etc/init.d/hpcc_common.in
+++ b/initfiles/bash/etc/init.d/hpcc_common.in
@@ -429,12 +429,10 @@ startCmd() {
        if [ ${RCSTART} -ne 0 ];then
           if [ ${DEBUG} != "NO_DEBUG" ]; then
               log_failure_msg "Pid or lock file exists, but process is not running"
-              removePid ${PIDPATH}
-              unlock ${LOCKPATH}
-          else
-              removePid ${PIDPATH}
-              unlock ${LOCKPATH}
           fi
+          cleanup_component
+          removePid ${PIDPATH}
+          unlock ${LOCKPATH}
        else
           if [ ${DEBUG} != "NO_DEBUG" ]; then
               log_failure_msg "Lock or Pid file already exists"
@@ -445,9 +443,9 @@ startCmd() {
           return ${RCSTART}
        fi
     fi
-    
+
     EXEC_COMMAND="${bin_path}/init_${compType} "
-    startcmd="${START_STOP_DAEMON} -S -p ${pid}/${compName}_init.pid -c ${user}:${group} -d ${compPath} -m -x ${EXEC_COMMAND} -b  >>${logFile} 2>&1"
+    startcmd="${START_STOP_DAEMON} -S -p ${pid}/${compName}_init.pid -c ${user}:${group} -d ${compPath} -m -x ${EXEC_COMMAND} -b >>${logFile} 2>&1"
 
     issueTime=`date`
     logCommand="COMMAND:: $startcmd  ::Issued at $issueTime "
@@ -532,13 +530,12 @@ stop_component() {
     if [ $RCSTOP -ne 0 ];then
        if [ ${DEBUG} != "NO_DEBUG" ]; then
           log_failure_msg "Failed: Process is not running"
-          removePid ${PIDPATH}
-          unlock ${LOCKPATH}
        else
           log_failure_msg "Already Stopped"
-          removePid ${PIDPATH}
-          unlock ${LOCKPATH}
        fi
+       cleanup_component
+       removePid ${PIDPATH}
+       unlock ${LOCKPATH}
        return 0
     fi
     
@@ -567,7 +564,7 @@ stop_component() {
                         if [ $__pidExists -ne 1 ];then
                             removePid ${PIDPATH}
                             unlock ${LOCKPATH}
-                            log_success_msg  
+                            log_success_msg
                             return 0
                         fi
                     fi
@@ -980,4 +977,69 @@ cluster_tools_init() {
    cluster_log_dir_owner=$(ls -ld $CLUSTER_LOG_DIR | awk '{print $3}')
    [ "$cluster_log_dir_owner" != "${user}" ] && ${_cmd_prefix} chown ${user}:${user} $CLUSTER_LOG_DIR
    
+}
+##
+## Cleanup component
+##
+cleanup_component() {
+
+  # used to get variables for frunssh
+  # Necessary for when we source in setvars, since we aren't using the start-stop-demon the $HOME will
+  # be set to /root or some other location, and not the appropriate directory, causing problems
+  # with $SSHidentityfile
+  set_environmentvars
+  HOME=${home}/${user}
+  instancedir=${runtime}/${compName}
+  source $instancedir/setvars
+
+  # grab the PID of our component, and in the case it doesn't exist, the pid of the init file (in case
+  # it's somehow is still alive)
+  local cpidpath=${COMPPIDPATH}
+  if [ "${compType}" = "thor" ] && [ ! -f "${cpidpath}" ]; then
+    # if run_thor is sent a SIGKILL, the normal COMPPIDPATH file will no longer exist, we catch this and
+    # fall back to the {compName}_master.pid file that will still be available.
+    cpidpath=$( echo $cpidpath | sed 's/\.pid/_master.pid/' )
+  fi
+  getPid ${cpidpath}
+  local mpid=$__pidValue
+  if [ $mpid -eq 0 ]; then
+    getPid ${PIDPATH}
+    mpid=$__pidValue
+  fi
+
+
+  # use the mpid we collected to grab the group pid of the process, to kill off all siblings at once
+  local pgid=$( ps -p $mpid -o pid,pgid | grep $mpid | awk '{ print $2 }' )
+
+  # start with SIGTERM and then follow up with SIGKILL if unsuccessful
+  if [ $pgid -ne 0 ] ; then
+    kill -15 -$pgid
+    sleep 1
+    local WAITTIME=5
+    local WAIT=0
+    while [[ ${WAIT} -lt ${WAITTIME} ]]; do
+      WAIT=`expr ${WAIT} + 1`
+      kill -0 -$pgid &> /dev/null
+      if [ $? -eq 0 ];then
+        if [ ${DEBUG} != "NO_DEBUG" ]; then      
+          echo "Waiting for ${compName} orphans to cleanup gracefully"
+        fi
+      elif [[ ${WAIT} -eq 5 ]]; then
+        if [ ${DEBUG} != "NO_DEBUG" ]; then
+          echo "sending SIGKILL to ${compName} orphans"
+        fi
+        kill -9 -$pgid
+      else
+        break
+      fi
+      sleep 1
+    done
+
+
+    # take care of thor slaves on remote nodes
+    if [ "${compType}" = "thor" ]; then
+      nslaves=$( cat $instancedir/uslaves.start | wc -l )
+      $bin_path/frunssh $instancedir/uslaves.start "/bin/sh -c '$bin_path/stop_slaves ${compName} ${PID_DIR}'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$nslaves &> /dev/null
+    fi
+  fi
 }
diff --git a/initfiles/componentfiles/thor/stop_thor b/initfiles/componentfiles/thor/stop_thor
--- a/initfiles/componentfiles/thor/stop_thor
+++ b/initfiles/componentfiles/thor/stop_thor
@@ -69,29 +69,29 @@ echo --------------------------
 echo stopping thor slaves 
 
 if [ "$localthor" = "true" ]; then
-    SLAVE_PID_NAME="$PID/${comp_base}_slave_*.pid"
-    slavepid=`cat ${SLAVE_PID_NAME} 2> /dev/null`
-    kill -9 $slavepid 2> /dev/null
+  SLAVE_PID_NAME="$PID/${comp_base}_slave_*.pid"
+  slavepid=`cat ${SLAVE_PID_NAME} 2> /dev/null`
+  kill -9 $slavepid 2> /dev/null
 else
-    # use 20 threads
-    # timeout of 60 seconds (in case slave busy)
-    # hard kill (called after master down anyway so going to stall)
-    if [ ! -r $instancedir/slaves ]; then
-        if [ ! -z ${THORPRIMARY} ]; then
-            groupName=${THORPRIMARY}
-        else
-            groupName=${THORNAME}
-        fi
-        daliadmin $DALISERVER dfsgroup ${groupName} > $instancedir/slaves
-        errcode=$?
-        if [ 0 != ${errcode} ]; then
-            echo 'failed to lookup dali group for $groupName'
-            exit 1
-        fi
+  # use 20 threads
+  # timeout of 60 seconds (in case slave busy)
+  # hard kill (called after master down anyway so going to stall)
+  if [ ! -r $instancedir/slaves ]; then
+    if [ ! -z ${THORPRIMARY} ]; then
+        groupName=${THORPRIMARY}
+    else
+        groupName=${THORNAME}
     fi
-    sort $instancedir/slaves | uniq > $instancedir/uslaves
-    nslaves=`cat $instancedir/uslaves.start | wc -l`
-    $deploydir/frunssh $instancedir/uslaves "/bin/sh -c '$deploydir/stop_slaves ${comp_base} $PATH_PRE $THORMASTER:$THORMASTERPORT'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$nslaves 2>&1 | egrep -v "no process killed"
-    echo slaves stopped
+    daliadmin $DALISERVER dfsgroup ${groupName} > $instancedir/slaves
+    errcode=$?
+    if [ 0 != ${errcode} ]; then
+        echo 'failed to lookup dali group for $groupName'
+        exit 1
+    fi
+  fi
 fi
 
+sort $instancedir/slaves | uniq > $instancedir/uslaves
+nslaves=`cat $instancedir/uslaves.start | wc -l`
+$deploydir/frunssh $instancedir/uslaves "/bin/sh -c '$deploydir/stop_slaves ${THORNAME} ${PID}'" -i:$SSHidentityfile -u:$SSHusername -pe:$SSHpassword -t:$SSHtimeout -a:$SSHretries -n:$nslaves 2>&1 | egrep -v "no process killed"
+echo slaves stopped
