HPCC-11156 Allow hpcc-run.sh run concurrently
1) Generate script hpcc-run_ which take only 1 input parameter: ip
2) If python 2.6+ installed it will run above script through cluster_script.py.
   It allows mulitple instances run simultanously. The default is 5.
   If no python 2.6+ found it will run the script sequentially
3) It follows original script logics:
   start: first start hpcc on the host which run dali, then start hpcc on rest hosts
   stop: first stop hpcc on all the hosts which do not have dali, then the host has dali.
4) Execution results will output to console. If "-s" provided these results will be saved
   under  /var/log/HPCCSystems/cluster/<command>/yyyymmdd_HHMMSS/
5) Log file is at /var/log/HPCCSystesm/cluster/XX_hpcc-run__yyyymmdd_HHMMSS.log
   For concurrent exection XX is "cc" If run sequentially it is "se".

diff --git a/initfiles/bash/etc/init.d/hpcc_common.in b/initfiles/bash/etc/init.d/hpcc_common.in
--- a/initfiles/bash/etc/init.d/hpcc_common.in
+++ b/initfiles/bash/etc/init.d/hpcc_common.in
@@ -26,7 +26,6 @@
 
 ###<REPLACE>###
 
-
 START_STOP_DAEMON=${INSTALL_DIR}/bin/start-stop-daemon
 
 which_service(){
@@ -920,13 +919,22 @@ run_cluster() {
    _log_file=${LOG_DIR}/cluster/se_$(basename $_cmd)_$(date +%Y%m%d_%H%M%S).log
    [ ! -d ${LOG_DIR}/cluster ] && mkdir -p ${LOG_DIR}/cluster
    [ -e $_log_file ] && rm -rf $_log_file
-   echo ""
-   echo  -ne "Execution progress: ${_progress}%, succeed: $_num_passed, failed: $_num_failed \r"
+   if [ "$RUN_CLUSTER_DISPLAY_OUTPUT" != "TRUE" ]
+   then
+      echo ""
+      echo  -ne "Execution progress: ${_progress}%, succeed: $_num_passed, failed: $_num_failed \r"
+   fi
    for ip in $IPS
    do
-      eval $_cmd $ip >> $_log_file 2>&1
+      if [ "$RUN_CLUSTER_DISPLAY_OUTPUT" = "TRUE" ]
+      then
+          echo
+          eval $_cmd $ip | tee -a $_log_file 2>&1
+      else
+          eval $_cmd $ip >> $_log_file 2>&1
+      fi
 
-      if [ $? -eq 0 ]
+      if [ ${PIPESTATUS[0]} -eq 0 ]
       then
          _num_passed=$(expr $_num_passed \+ 1)
       else
@@ -934,8 +942,11 @@ run_cluster() {
       fi
 
       _num_processed=$(expr $_num_processed \+ 1)
-      _progress=$(expr $_num_processed \* 100  / $_num_hosts)
-      echo  -ne "Execution progress: ${_progress}%, succeed: $_num_passed, failed: $_num_failed \r"
+      if [ "$RUN_CLUSTER_DISPLAY_OUTPUT" != "TRUE" ]
+      then
+         _progress=$(expr $_num_processed \* 100  / $_num_hosts)
+         echo  -ne "Execution progress: ${_progress}%, succeed: $_num_passed, failed: $_num_failed \r"
+      fi
    done
 
    echo ""
