HPCC-00000 PKI setup for make install
- Be able to provide CA address on make install command line

Signed-off-by: mayx <yanrui.ma@lexisnexisrisk.com>

diff --git a/initfiles/bash/etc/init.d/setupPKI.in b/initfiles/bash/etc/init.d/setupPKI.in
--- a/initfiles/bash/etc/init.d/setupPKI.in
+++ b/initfiles/bash/etc/init.d/setupPKI.in
@@ -43,13 +43,22 @@ else
 fi
 
 if [ ! -e ${homePath}/certificate/certificate.pem ]; then
-    #openssl req -new -key ${homePath}/certificate/key.pem -keyform PEM -x509 \
-    #    -days 365 -out ${homePath}/certificate/certificate.pem \
-    #    -batch 1>/dev/null 2>&1
-    openssl req -new -key ${homePath}/certificate/key.pem -out ${homePath}/certificate/csr.pem
-    cfssl sign -config ${INSTALL_DIR}/etc/init.d/sign_config.json ${homePath}/certificate/csr.pem | cfssljson -bare ${homePath}/certificate/certificate
-    printf "CA signed Certificate installed for user %-12s ..." "$user"
-    log_success_msg
+    if [ "${CALOCATION}" = "" ]; then
+        openssl req -new -key ${homePath}/certificate/key.pem -keyform PEM -x509 \
+        -days 365 -out ${homePath}/certificate/certificate.pem \
+        -batch 1>/dev/null 2>&1
+        printf "Self signed Certificate installed for user %-12s ..." "$user"
+    else
+        openssl req -new -key ${homePath}/certificate/key.pem -out ${homePath}/certificate/csr.pem
+        cfssl sign -remote ${CALOCATION} ${homePath}/certificate/csr.pem | cfssljson -bare ${homePath}/certificate/certificate
+        if [ ! -e ${homePath}/certificate/certificate.pem ]; then
+            printf "Failed to generate certificate\n"
+            exit 1
+        else
+            printf "CA signed Certificate installed for user %-12s ..." "$user"
+            log_success_msg
+        fi
+    fi
 else
     printf "Certificate already installed for %-9s ..." "$user"
     log_success_msg
