HPCC-34973 Include Arm builds for u22.04 and u24.04 targets
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

diff --git a/.github/workflows/build-docker-enterprise.yml b/.github/workflows/build-docker-enterprise.yml
--- a/.github/workflows/build-docker-enterprise.yml
+++ b/.github/workflows/build-docker-enterprise.yml
@@ -21,6 +21,11 @@ on:
         required: false
         default: false
         type: boolean
+      architecture:
+        description: 'Architecture, either -arm or empty string'
+        required: false
+        type: string
+        default: ''
 
   workflow_dispatch:
     inputs:
@@ -42,11 +47,16 @@ on:
         description: 'Build Docker Image'
         required: false
         default: false
+      architecture:
+        description: 'Architecture, either -arm or empty string'
+        required: false
+        type: string
+        default: ''
 
 jobs:
   build:
     name: Build enterprise platform
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04${{ inputs.architecture }}
     steps:
       - name: Free additional disk space (remove Android SDK + Tools)
         continue-on-error: true
@@ -111,8 +121,8 @@ jobs:
           echo "vcpkg_sha_short=$vcpkg_sha_short" >> $GITHUB_OUTPUT
           docker_build_label=hpccsystems/platform-build-${{ inputs.os }}
           echo "docker_build_label=$docker_build_label" >> $GITHUB_OUTPUT
-          echo "docker_tag=$docker_build_label:$vcpkg_sha_short" >> $GITHUB_OUTPUT
-          echo "docker_tag_candidate_base=$docker_build_label:$candidate_base_branch" >> $GITHUB_OUTPUT
+          echo "docker_tag=$docker_build_label:$vcpkg_sha_short${{ inputs.architecture }}" >> $GITHUB_OUTPUT
+          echo "docker_tag_candidate_base=$docker_build_label:$candidate_base_branch${{ inputs.architecture }}" >> $GITHUB_OUTPUT
   
       - name: Print Vars
         run: echo "${{ toJson(steps.vars.outputs)}}"
@@ -145,7 +155,7 @@ jobs:
           push: ${{ github.repository_owner == 'hpcc-systems' }}
           load: ${{ github.repository_owner != 'hpcc-systems' }}
           build-args: |
-            VCPKG_REF=${{ steps.vars.outputs.vcpkg_sha_short }}
+            VCPKG_REF=${{ steps.vars.outputs.vcpkg_sha_short }}${{ inputs.architecture }}
           tags: |
             ${{ steps.vars.outputs.docker_tag_candidate_base }}
           cache-from: |
@@ -170,10 +180,15 @@ jobs:
         run: |
           cd ${{ steps.vars.outputs.folder_build }}
           version=$(echo "${{ steps.vars.outputs.internal_tag }}" | sed 's/internal_//')
+          arch=$(dpkg --print-architecture)
+          if [ $? -ne 0 ] || [ -z "$arch" ]; then
+            echo "Error: Failed to determine architecture with 'dpkg --print-architecture'."
+            exit 1
+          fi
           packages=($(ls -1 hpccsystems-*.deb ))
           for _package in ${packages[@]}; do
             distribution=$( echo "${_package}" | sed "s/^.*${version}//" | awk -F '_' '{print $1;}' )
-            curl -u${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} -XPUT "https://${{ secrets.JFROG_REGISTRY }}/hpccpl-debian-local/pool/EE/${_package};deb.distribution=${distribution};deb.component=EE;deb.architecture=amd64" -T ${{ steps.vars.outputs.folder_build }}/${_package} 
+            curl -u${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} -XPUT "https://${{ secrets.JFROG_REGISTRY }}/hpccpl-debian-local/pool/EE/${_package};deb.distribution=${distribution};deb.component=EE;deb.architecture=${arch}" -T ${{ steps.vars.outputs.folder_build }}/${_package} 
           done
 
       - name: Cleanup Environment
